Add arm64 image creation.

diff --git a/.github/workflows/create_images.yml b/.github/workflows/create_images.yml
--- a/.github/workflows/create_images.yml
+++ b/.github/workflows/create_images.yml
@@ -63,16 +63,18 @@ jobs:
       #       # Logout of Docker Hub with hub-tool
       #       ./hub-tool logout
       #     fi          
-      # - name: Create arm64 image and tag
-      #   run: |
-      #     docker buildx build --platform linux/arm64 -t dhub-test:test__arm64 .
-      #     docker tag dhub-test:test__arm64 tjdahl/dhub-test:test__arm64
-      # - name: Test built image
-      #   run: |
-      #     if [[ $(docker run --rm tjdahl/dhub-test:test__arm64) != "test" ]]; then
-      #       echo "Arm64 image failed to build properly."
-      #       exit 1;
-      #     fi
+
+      - name: Create arm64 image and tag
+        run: |
+          docker buildx build --platform linux/arm64 -t tjdahl/dhub-test:${{ github.event.client_payload.NEW_ARM_TAG }} .
+
+      - name: Test built image
+        run: |
+          if [[ $(docker run --rm tjdahl/dhub-test:${{ github.event.client_payload.NEW_ARM_TAG }}) != "test" ]]; then
+            echo "Arm64 image failed to build properly."
+            exit 1;
+          fi
+
       # - name: Log into Docker Hub with docker
       #   env:
       #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
