Comment out ARM64 image test.

diff --git a/.github/workflows/create_arm64_image.yml b/.github/workflows/create_arm64_image.yml
--- a/.github/workflows/create_arm64_image.yml
+++ b/.github/workflows/create_arm64_image.yml
@@ -22,12 +22,13 @@ jobs:
             docker buildx build --platform linux/arm64 -t tjdahl/dhub-test:${{ github.event.client_payload.NEW_AMD_TAG }} .
           fi
 
-      - name: Test built image
-        run: |
-          if [[ $(docker run --rm tjdahl/dhub-test:${{ github.event.client_payload.NEW_AMD_TAG }}) != "test" ]]; then
-            echo "Arm64 image failed to build properly."
-            exit 1;
-          fi
+      # CANNOT TEST ARM64 IMAGE ON AMD64 PLATFORM
+      # - name: Test built image
+      #   run: |
+      #     if [[ $(docker run --rm tjdahl/dhub-test:${{ github.event.client_payload.NEW_AMD_TAG }}) != "test" ]]; then
+      #       echo "Arm64 image failed to build properly."
+      #       exit 1;
+      #     fi
 
       - name: Log into Docker Hub with docker
         env:
